import jsPDF from 'jspdf';
import { Conversation, Message } from '../types';
import { DateUtils } from './dateUtils';

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}

function addPDFHeader(pdf: jsPDF, conversation: Conversation, margin: number): number {
  let yPosition = margin;

  // Header
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Atticus - In-House AI Counsel', margin, yPosition);
  yPosition += 10;

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Conversation: ${conversation.title}`, margin, yPosition);
  yPosition += 6;

  const dateStr = DateUtils.formatDateTime(conversation.createdAt);
  pdf.text(`Date: ${dateStr}`, margin, yPosition);
  yPosition += 6;

  if (conversation.practiceArea) {
    pdf.text(`Practice Area: ${conversation.practiceArea}`, margin, yPosition);
    yPosition += 6;
  }

  // Show AI models used
  if (conversation.selectedModels && conversation.selectedModels.length > 0) {
    const models = conversation.selectedModels
      .map(m => `${m.providerId}/${m.modelId}`)
      .join(', ');
    pdf.text(`AI Models: ${models}`, margin, yPosition);
    yPosition += 6;
  } else if (conversation.provider) {
    const modelInfo = conversation.model ? ` (${conversation.model})` : '';
    pdf.text(`Provider: ${conversation.provider}${modelInfo}`, margin, yPosition);
    yPosition += 6;
  }

  // Show jurisdictions if specified
  if (conversation.selectedJurisdictions && conversation.selectedJurisdictions.length > 0) {
    pdf.text(`Jurisdictions: ${conversation.selectedJurisdictions.join(', ')}`, margin, yPosition);
    yPosition += 6;
  }

  yPosition += 4;
  return yPosition;
}

function addMessageAttachments(pdf: jsPDF, attachments: Array<{ name: string; size: number }>, margin: number, pageHeight: number, yPosition: number): number {
  let y = yPosition + 3;
  pdf.setFontSize(9);
  pdf.setTextColor(100, 100, 100);

  for (const attachment of attachments) {
    if (y > pageHeight - 20) {
      pdf.addPage();
      y = margin;
    }
    pdf.text(`📎 ${attachment.name} (${formatFileSize(attachment.size)})`, margin + 5, y);
    y += 5;
  }

  pdf.setTextColor(0, 0, 0);
  return y;
}

function addPDFMessage(pdf: jsPDF, message: Message, margin: number, maxWidth: number, pageHeight: number, yPosition: number): number {
  let y = yPosition;

  // Check if we need a new page
  if (y > pageHeight - 30) {
    pdf.addPage();
    y = margin;
  }

  // Message header
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  const role = message.role === 'user' ? 'You' : 'Assistant';
  const timestamp = DateUtils.formatTime(message.timestamp);
  pdf.text(`${role} (${timestamp})`, margin, y);
  y += 7;

  // Message content
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const lines = pdf.splitTextToSize(message.content, maxWidth);

  for (const line of lines) {
    if (y > pageHeight - 20) {
      pdf.addPage();
      y = margin;
    }
    pdf.text(line, margin, y);
    y += 5;
  }

  // Attachments
  if (message.attachments && message.attachments.length > 0) {
    y = addMessageAttachments(pdf, message.attachments, margin, pageHeight, y);
  }

  return y + 8;
}

function addPDFFooters(pdf: jsPDF, pageWidth: number, pageHeight: number): void {
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    pdf.text(
      'Generated by Atticus - In-House AI Counsel',
      pageWidth / 2,
      pageHeight - 6,
      { align: 'center' }
    );
  }
}

export async function exportConversationToPDF(conversation: Conversation): Promise<string> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  // Add header
  let yPosition = addPDFHeader(pdf, conversation, margin);

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Add messages
  for (const message of conversation.messages) {
    yPosition = addPDFMessage(pdf, message, margin, maxWidth, pageHeight, yPosition);
  }

  // Add footers
  addPDFFooters(pdf, pageWidth, pageHeight);

  // Return as base64
  return pdf.output('datauristring').split(',')[1];
}

export async function downloadPDF(conversation: Conversation): Promise<void> {
  try {
    const pdfData = await exportConversationToPDF(conversation);
    // Sanitize filename by replacing all non-alphanumeric characters with hyphens
    const filename = `atticus-${conversation.title.split('').map(char => /[a-z0-9]/i.test(char) ? char : '-').join('').toLowerCase()}-${Date.now()}.pdf`;

    const result = await (globalThis as any).electronAPI.savePDF({
      filename,
      data: pdfData,
    });

    if (result.success && result.data) {
      console.log('PDF saved:', result.data.filepath);
    }
  } catch (error) {
    console.error('Error downloading PDF:', error);
    throw error;
  }
}
